server:
  port: 8095
spring:
  application:
   name: logans

   # 指定静态资源的路径
  thymeleaf:
    prefix: classpath:/public/
    mode: LEGACYHTML5
  resources:
   static-locations: classpath:/static/,classpath:/public/,classpath:/META-INF/resources/

# 数据库链接
datasource:
   master:
      url: jdbc:mysql://192.168.100.13:3306/dev_logans?useUnicode=true&characterEncoding=utf-8&useSSL=true

# 并发执行任务数
task:
  pool-size: 30

# 链接ES参数
# 生产环境 ip:172.17.0.61 port:9200
# 测试环境 ip:192.168.100.40 port:9201
# 研发环境 ip:192.168.100.30 port:9200
elastic-search:
  ip: 192.168.100.30
  port: 9200

# hbase配置信息
# 生产环境：hb-2zejh008601i8n321-001.hbase.rds.aliyuncs.com
# 研发环境：master, slave01, slave02
hbase:
  config:
    hbase.zookeeper.quorum: master,slave01,slave02
    hbase.zookeeper.property.clientPort: 2181
